job: extension
config:
  name: flux_lora_test2
  process:
  - type: sd_trainer
    training_folder: ./output
    model:
      name_or_path: black-forest-labs/FLUX.2-klein-base-4B
      is_flux: true
      quantize: true
      quantize_te: true
      low_vram: false
      layer_offloading: false
      arch: flux2_klein
      vae_path: C:\Projects\AI_Image_Trainer\models\flux2_vae\ae.safetensors
    network:
      type: lora
      linear: 32
      linear_alpha: 16
    save:
      dtype: bf16
      save_every: 300
      max_step_saves_to_keep: 3
    datasets:
    - folder_path: C:/Projects/AI_Image_Trainer/datasets/Necronomicon/Fixed2
      caption_ext: txt
      num_repeats: 10
    train:
      batch_size: 1
      steps: 1248
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      learning_rate: 0.0002
      lr_scheduler: constant
      optimizer: adamw8bit
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      max_denoising_steps: 1000
      cache_latents: true
      cache_text_encoder_outputs: true
      dtype: bf16
      max_grad_norm: 1.0
